#!/usr/bin/env bash

# switch to --list-style=tty with --labels to debug tree

NODE_ENV=devel ldn exec http://localhost:3000/sitemap --cmd 'ldn meta' --json \
  --pattern-file docs.conf \
  --exclude=/docs/browser-update \
    | NODE_ENV=devel ldn tree --list-style=jade \
      --pluck=/docs --suppress-root --sort=label \
      > www/src/docs/list.jade
